# FlexibleInputStackBar document generator jazzy settings

copyright: Copyright 2019 FlexibleInputStackBar
author: Kazumasa Shimomura
xcodebuild_arguments: [-target, FlexibleInputStackBar]
clean: true
output: ./docs
